# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_form_statistics.ui'
#
# Created: Mon Aug 20 13:44:42 2012
#      by: PyQt4 UI code generator 4.9
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName(_fromUtf8("Frame"))
        Frame.resize(729, 610)
        self.tab_node = QtGui.QTableWidget(Frame)
        self.tab_node.setGeometry(QtCore.QRect(10, 10, 711, 201))
        self.tab_node.setObjectName(_fromUtf8("tab_node"))
        self.tab_node.setColumnCount(7)
        self.tab_node.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tab_node.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tab_node.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tab_node.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tab_node.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tab_node.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tab_node.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tab_node.setHorizontalHeaderItem(6, item)
        self.tab_zone = QtGui.QTableWidget(Frame)
        self.tab_zone.setGeometry(QtCore.QRect(10, 220, 711, 211))
        self.tab_zone.setObjectName(_fromUtf8("tab_zone"))
        self.tab_zone.setColumnCount(7)
        self.tab_zone.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tab_zone.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tab_zone.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tab_zone.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tab_zone.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tab_zone.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tab_zone.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tab_zone.setHorizontalHeaderItem(6, item)
        self.btn_refurbish = QtGui.QPushButton(Frame)
        self.btn_refurbish.setGeometry(QtCore.QRect(510, 570, 75, 23))
        self.btn_refurbish.setObjectName(_fromUtf8("btn_refurbish"))
        self.btn_close = QtGui.QPushButton(Frame)
        self.btn_close.setGeometry(QtCore.QRect(620, 570, 75, 23))
        self.btn_close.setObjectName(_fromUtf8("btn_close"))
        self.groupBox = QtGui.QGroupBox(Frame)
        self.groupBox.setGeometry(QtCore.QRect(10, 440, 711, 111))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.edt_onlinezone = QtGui.QLineEdit(self.groupBox)
        self.edt_onlinezone.setGeometry(QtCore.QRect(490, 60, 121, 20))
        self.edt_onlinezone.setObjectName(_fromUtf8("edt_onlinezone"))
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(340, 30, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.edt_onlinenode = QtGui.QLineEdit(self.groupBox)
        self.edt_onlinenode.setGeometry(QtCore.QRect(490, 30, 121, 20))
        self.edt_onlinenode.setObjectName(_fromUtf8("edt_onlinenode"))
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(10, 80, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 20, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 50, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.edt_sysfree = QtGui.QLineEdit(self.groupBox)
        self.edt_sysfree.setGeometry(QtCore.QRect(160, 50, 121, 20))
        self.edt_sysfree.setObjectName(_fromUtf8("edt_sysfree"))
        self.edt_sysavail = QtGui.QLineEdit(self.groupBox)
        self.edt_sysavail.setGeometry(QtCore.QRect(160, 80, 121, 20))
        self.edt_sysavail.setObjectName(_fromUtf8("edt_sysavail"))
        self.edt_sysall = QtGui.QLineEdit(self.groupBox)
        self.edt_sysall.setGeometry(QtCore.QRect(160, 20, 121, 20))
        self.edt_sysall.setObjectName(_fromUtf8("edt_sysall"))
        self.label_5 = QtGui.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(340, 60, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))

        self.retranslateUi(Frame)
        QtCore.QObject.connect(self.btn_close, QtCore.SIGNAL(_fromUtf8("clicked()")), Frame.close)
        QtCore.QMetaObject.connectSlotsByName(Frame)
        Frame.setTabOrder(self.btn_refurbish, self.btn_close)
        Frame.setTabOrder(self.btn_close, self.edt_sysall)
        Frame.setTabOrder(self.edt_sysall, self.edt_sysfree)
        Frame.setTabOrder(self.edt_sysfree, self.edt_sysavail)
        Frame.setTabOrder(self.edt_sysavail, self.edt_onlinenode)
        Frame.setTabOrder(self.edt_onlinenode, self.edt_onlinezone)
        Frame.setTabOrder(self.edt_onlinezone, self.tab_node)
        Frame.setTabOrder(self.tab_node, self.tab_zone)

    def retranslateUi(self, Frame):
        Frame.setWindowTitle(QtGui.QApplication.translate("Frame", "Frame", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tab_node.horizontalHeaderItem(0)
        item.setText(QtGui.QApplication.translate("Frame", "节点编号", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tab_node.horizontalHeaderItem(1)
        item.setText(QtGui.QApplication.translate("Frame", "节点地址", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tab_node.horizontalHeaderItem(2)
        item.setText(QtGui.QApplication.translate("Frame", "节点状态", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tab_node.horizontalHeaderItem(3)
        item.setText(QtGui.QApplication.translate("Frame", "当前连接数", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tab_node.horizontalHeaderItem(4)
        item.setText(QtGui.QApplication.translate("Frame", "最大空间(MB)", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tab_node.horizontalHeaderItem(5)
        item.setText(QtGui.QApplication.translate("Frame", "已用空间(MB)", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tab_node.horizontalHeaderItem(6)
        item.setText(QtGui.QApplication.translate("Frame", "空间利用率", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tab_zone.horizontalHeaderItem(0)
        item.setText(QtGui.QApplication.translate("Frame", "节点编号", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tab_zone.horizontalHeaderItem(1)
        item.setText(QtGui.QApplication.translate("Frame", "节点地址", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tab_zone.horizontalHeaderItem(2)
        item.setText(QtGui.QApplication.translate("Frame", "存储区编号", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tab_zone.horizontalHeaderItem(3)
        item.setText(QtGui.QApplication.translate("Frame", "存储区路径", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tab_zone.horizontalHeaderItem(4)
        item.setText(QtGui.QApplication.translate("Frame", "最大空间(MB)", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tab_zone.horizontalHeaderItem(5)
        item.setText(QtGui.QApplication.translate("Frame", "已用空间(MB)", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tab_zone.horizontalHeaderItem(6)
        item.setText(QtGui.QApplication.translate("Frame", "空间利用率", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_refurbish.setText(QtGui.QApplication.translate("Frame", "刷新", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_close.setText(QtGui.QApplication.translate("Frame", "退出", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Frame", "系统总览", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Frame", "在线节点/节点总数", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Frame", "空间利用率", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Frame", "系统总空间(MB)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Frame", "剩余总空间(MB)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Frame", "在线存储区/存储区总数", None, QtGui.QApplication.UnicodeUTF8))

