# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_form_taskmgr.ui'
#
# Created: Mon Aug 20 13:44:43 2012
#      by: PyQt4 UI code generator 4.9
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName(_fromUtf8("Frame"))
        Frame.resize(475, 417)
        self.tab_taskmgr = QtGui.QTableWidget(Frame)
        self.tab_taskmgr.setGeometry(QtCore.QRect(10, 10, 221, 361))
        self.tab_taskmgr.setObjectName(_fromUtf8("tab_taskmgr"))
        self.tab_taskmgr.setColumnCount(3)
        self.tab_taskmgr.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tab_taskmgr.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tab_taskmgr.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tab_taskmgr.setHorizontalHeaderItem(2, item)
        self.btn_addtask = QtGui.QPushButton(Frame)
        self.btn_addtask.setGeometry(QtCore.QRect(30, 380, 75, 23))
        self.btn_addtask.setObjectName(_fromUtf8("btn_addtask"))
        self.btn_deltask = QtGui.QPushButton(Frame)
        self.btn_deltask.setGeometry(QtCore.QRect(130, 380, 75, 23))
        self.btn_deltask.setObjectName(_fromUtf8("btn_deltask"))
        self.btn_close = QtGui.QPushButton(Frame)
        self.btn_close.setGeometry(QtCore.QRect(370, 380, 75, 23))
        self.btn_close.setObjectName(_fromUtf8("btn_close"))
        self.AttrPage = QtGui.QStackedWidget(Frame)
        self.AttrPage.setGeometry(QtCore.QRect(240, 10, 221, 361))
        self.AttrPage.setObjectName(_fromUtf8("AttrPage"))
        self.task_view = QtGui.QWidget()
        self.task_view.setObjectName(_fromUtf8("task_view"))
        self.groupBox = QtGui.QGroupBox(self.task_view)
        self.groupBox.setGeometry(QtCore.QRect(0, 0, 221, 361))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.edt_taskname = QtGui.QLineEdit(self.groupBox)
        self.edt_taskname.setGeometry(QtCore.QRect(80, 30, 131, 20))
        self.edt_taskname.setObjectName(_fromUtf8("edt_taskname"))
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 60, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 30, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.edt_editor = QtGui.QLineEdit(self.groupBox)
        self.edt_editor.setGeometry(QtCore.QRect(80, 60, 131, 20))
        self.edt_editor.setObjectName(_fromUtf8("edt_editor"))
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(10, 90, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(10, 150, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.date_starttime = QtGui.QDateEdit(self.groupBox)
        self.date_starttime.setGeometry(QtCore.QRect(10, 120, 81, 22))
        self.date_starttime.setObjectName(_fromUtf8("date_starttime"))
        self.date_endtime = QtGui.QDateEdit(self.groupBox)
        self.date_endtime.setGeometry(QtCore.QRect(130, 120, 81, 22))
        self.date_endtime.setObjectName(_fromUtf8("date_endtime"))
        self.label_6 = QtGui.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(100, 120, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.txtedt_taskmark = QtGui.QTextEdit(self.groupBox)
        self.txtedt_taskmark.setGeometry(QtCore.QRect(10, 180, 201, 131))
        self.txtedt_taskmark.setObjectName(_fromUtf8("txtedt_taskmark"))
        self.btn_saveinfo = QtGui.QPushButton(self.groupBox)
        self.btn_saveinfo.setGeometry(QtCore.QRect(30, 320, 75, 23))
        self.btn_saveinfo.setObjectName(_fromUtf8("btn_saveinfo"))
        self.btn_resetting = QtGui.QPushButton(self.groupBox)
        self.btn_resetting.setGeometry(QtCore.QRect(130, 320, 75, 23))
        self.btn_resetting.setObjectName(_fromUtf8("btn_resetting"))
        self.AttrPage.addWidget(self.task_view)
        self.creat_task = QtGui.QWidget()
        self.creat_task.setObjectName(_fromUtf8("creat_task"))
        self.groupBox_2 = QtGui.QGroupBox(self.creat_task)
        self.groupBox_2.setGeometry(QtCore.QRect(0, 0, 221, 361))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.edt_newtaskname = QtGui.QLineEdit(self.groupBox_2)
        self.edt_newtaskname.setGeometry(QtCore.QRect(80, 30, 131, 20))
        self.edt_newtaskname.setObjectName(_fromUtf8("edt_newtaskname"))
        self.label_7 = QtGui.QLabel(self.groupBox_2)
        self.label_7.setGeometry(QtCore.QRect(10, 30, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_8 = QtGui.QLabel(self.groupBox_2)
        self.label_8.setGeometry(QtCore.QRect(10, 70, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_9 = QtGui.QLabel(self.groupBox_2)
        self.label_9.setGeometry(QtCore.QRect(10, 130, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.date_newstarttime = QtGui.QDateEdit(self.groupBox_2)
        self.date_newstarttime.setGeometry(QtCore.QRect(10, 100, 81, 22))
        self.date_newstarttime.setDate(QtCore.QDate(2012, 1, 1))
        self.date_newstarttime.setObjectName(_fromUtf8("date_newstarttime"))
        self.date_newendtime = QtGui.QDateEdit(self.groupBox_2)
        self.date_newendtime.setGeometry(QtCore.QRect(130, 100, 81, 22))
        self.date_newendtime.setDate(QtCore.QDate(2012, 1, 1))
        self.date_newendtime.setObjectName(_fromUtf8("date_newendtime"))
        self.label_10 = QtGui.QLabel(self.groupBox_2)
        self.label_10.setGeometry(QtCore.QRect(100, 100, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.txtedt_newtaskmark = QtGui.QTextEdit(self.groupBox_2)
        self.txtedt_newtaskmark.setGeometry(QtCore.QRect(10, 160, 201, 131))
        self.txtedt_newtaskmark.setObjectName(_fromUtf8("txtedt_newtaskmark"))
        self.btn_newsaveinfo = QtGui.QPushButton(self.groupBox_2)
        self.btn_newsaveinfo.setGeometry(QtCore.QRect(30, 320, 75, 23))
        self.btn_newsaveinfo.setObjectName(_fromUtf8("btn_newsaveinfo"))
        self.btn_cancel = QtGui.QPushButton(self.groupBox_2)
        self.btn_cancel.setGeometry(QtCore.QRect(130, 320, 75, 23))
        self.btn_cancel.setObjectName(_fromUtf8("btn_cancel"))
        self.AttrPage.addWidget(self.creat_task)

        self.retranslateUi(Frame)
        self.AttrPage.setCurrentIndex(1)
        QtCore.QObject.connect(self.btn_close, QtCore.SIGNAL(_fromUtf8("clicked()")), Frame.close)
        QtCore.QMetaObject.connectSlotsByName(Frame)
        Frame.setTabOrder(self.btn_addtask, self.btn_deltask)
        Frame.setTabOrder(self.btn_deltask, self.edt_taskname)
        Frame.setTabOrder(self.edt_taskname, self.edt_editor)
        Frame.setTabOrder(self.edt_editor, self.date_starttime)
        Frame.setTabOrder(self.date_starttime, self.date_endtime)
        Frame.setTabOrder(self.date_endtime, self.txtedt_taskmark)
        Frame.setTabOrder(self.txtedt_taskmark, self.btn_saveinfo)
        Frame.setTabOrder(self.btn_saveinfo, self.btn_resetting)
        Frame.setTabOrder(self.btn_resetting, self.btn_close)
        Frame.setTabOrder(self.btn_close, self.tab_taskmgr)

    def retranslateUi(self, Frame):
        Frame.setWindowTitle(QtGui.QApplication.translate("Frame", "任务管理", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tab_taskmgr.horizontalHeaderItem(0)
        item.setText(QtGui.QApplication.translate("Frame", "序号", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tab_taskmgr.horizontalHeaderItem(1)
        item.setText(QtGui.QApplication.translate("Frame", "任务名称", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tab_taskmgr.horizontalHeaderItem(2)
        item.setText(QtGui.QApplication.translate("Frame", "创建时间", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_addtask.setText(QtGui.QApplication.translate("Frame", "创建任务", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_deltask.setText(QtGui.QApplication.translate("Frame", "删除任务", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_close.setText(QtGui.QApplication.translate("Frame", "关闭", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Frame", "任务属性", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Frame", "创建者", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Frame", "任务名称", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Frame", "影像检索范围", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Frame", "任务描述", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Frame", "至", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_saveinfo.setText(QtGui.QApplication.translate("Frame", "保存", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_resetting.setText(QtGui.QApplication.translate("Frame", "重置", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("Frame", "创建新任务", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Frame", "任务名称", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Frame", "影像检索范围", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("Frame", "任务描述", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("Frame", "至", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_newsaveinfo.setText(QtGui.QApplication.translate("Frame", "创建", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_cancel.setText(QtGui.QApplication.translate("Frame", "取消", None, QtGui.QApplication.UnicodeUTF8))

