# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_form_usermgr.ui'
#
# Created: Mon Aug 20 13:44:43 2012
#      by: PyQt4 UI code generator 4.9
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName(_fromUtf8("Frame"))
        Frame.resize(471, 335)
        self.btn_adduser = QtGui.QPushButton(Frame)
        self.btn_adduser.setGeometry(QtCore.QRect(30, 300, 75, 23))
        self.btn_adduser.setObjectName(_fromUtf8("btn_adduser"))
        self.btn_deluser = QtGui.QPushButton(Frame)
        self.btn_deluser.setGeometry(QtCore.QRect(130, 300, 75, 23))
        self.btn_deluser.setObjectName(_fromUtf8("btn_deluser"))
        self.btn_close = QtGui.QPushButton(Frame)
        self.btn_close.setGeometry(QtCore.QRect(380, 300, 75, 23))
        self.btn_close.setObjectName(_fromUtf8("btn_close"))
        self.AttrPage = QtGui.QStackedWidget(Frame)
        self.AttrPage.setGeometry(QtCore.QRect(240, 10, 221, 281))
        self.AttrPage.setObjectName(_fromUtf8("AttrPage"))
        self.user_view = QtGui.QWidget()
        self.user_view.setObjectName(_fromUtf8("user_view"))
        self.groupBox_2 = QtGui.QGroupBox(self.user_view)
        self.groupBox_2.setEnabled(True)
        self.groupBox_2.setGeometry(QtCore.QRect(0, 0, 221, 281))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.edt_view_username = QtGui.QLineEdit(self.groupBox_2)
        self.edt_view_username.setGeometry(QtCore.QRect(80, 60, 131, 20))
        self.edt_view_username.setObjectName(_fromUtf8("edt_view_username"))
        self.label_7 = QtGui.QLabel(self.groupBox_2)
        self.label_7.setGeometry(QtCore.QRect(10, 90, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_8 = QtGui.QLabel(self.groupBox_2)
        self.label_8.setGeometry(QtCore.QRect(10, 60, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.edt_view_passward = QtGui.QLineEdit(self.groupBox_2)
        self.edt_view_passward.setGeometry(QtCore.QRect(80, 90, 131, 20))
        self.edt_view_passward.setObjectName(_fromUtf8("edt_view_passward"))
        self.btn_revise = QtGui.QPushButton(self.groupBox_2)
        self.btn_revise.setGeometry(QtCore.QRect(30, 230, 75, 23))
        self.btn_revise.setObjectName(_fromUtf8("btn_revise"))
        self.btn_resetting = QtGui.QPushButton(self.groupBox_2)
        self.btn_resetting.setGeometry(QtCore.QRect(130, 230, 75, 23))
        self.btn_resetting.setObjectName(_fromUtf8("btn_resetting"))
        self.label_10 = QtGui.QLabel(self.groupBox_2)
        self.label_10.setGeometry(QtCore.QRect(10, 150, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.edt_view_createtime = QtGui.QLineEdit(self.groupBox_2)
        self.edt_view_createtime.setGeometry(QtCore.QRect(80, 150, 131, 20))
        self.edt_view_createtime.setObjectName(_fromUtf8("edt_view_createtime"))
        self.label_11 = QtGui.QLabel(self.groupBox_2)
        self.label_11.setGeometry(QtCore.QRect(10, 120, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_11.setFont(font)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.combo_view_usertype = QtGui.QComboBox(self.groupBox_2)
        self.combo_view_usertype.setGeometry(QtCore.QRect(80, 120, 131, 22))
        self.combo_view_usertype.setObjectName(_fromUtf8("combo_view_usertype"))
        self.AttrPage.addWidget(self.user_view)
        self.add_user = QtGui.QWidget()
        self.add_user.setObjectName(_fromUtf8("add_user"))
        self.groupBox = QtGui.QGroupBox(self.add_user)
        self.groupBox.setEnabled(True)
        self.groupBox.setGeometry(QtCore.QRect(0, 0, 221, 281))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.edt_username = QtGui.QLineEdit(self.groupBox)
        self.edt_username.setGeometry(QtCore.QRect(80, 60, 131, 20))
        self.edt_username.setObjectName(_fromUtf8("edt_username"))
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 90, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 60, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.edt_passward = QtGui.QLineEdit(self.groupBox)
        self.edt_passward.setGeometry(QtCore.QRect(80, 90, 131, 20))
        self.edt_passward.setObjectName(_fromUtf8("edt_passward"))
        self.btn_saveinfo = QtGui.QPushButton(self.groupBox)
        self.btn_saveinfo.setGeometry(QtCore.QRect(30, 230, 75, 23))
        self.btn_saveinfo.setObjectName(_fromUtf8("btn_saveinfo"))
        self.btn_cancel = QtGui.QPushButton(self.groupBox)
        self.btn_cancel.setGeometry(QtCore.QRect(130, 230, 75, 23))
        self.btn_cancel.setObjectName(_fromUtf8("btn_cancel"))
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(10, 120, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.edt_confirmpass = QtGui.QLineEdit(self.groupBox)
        self.edt_confirmpass.setGeometry(QtCore.QRect(80, 120, 131, 20))
        self.edt_confirmpass.setObjectName(_fromUtf8("edt_confirmpass"))
        self.label_5 = QtGui.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(10, 150, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.combo_usertype = QtGui.QComboBox(self.groupBox)
        self.combo_usertype.setGeometry(QtCore.QRect(80, 150, 131, 22))
        self.combo_usertype.setObjectName(_fromUtf8("combo_usertype"))
        self.AttrPage.addWidget(self.add_user)
        self.tab_usermgr = QtGui.QTableWidget(Frame)
        self.tab_usermgr.setGeometry(QtCore.QRect(10, 10, 221, 281))
        self.tab_usermgr.setObjectName(_fromUtf8("tab_usermgr"))
        self.tab_usermgr.setColumnCount(0)
        self.tab_usermgr.setRowCount(0)

        self.retranslateUi(Frame)
        self.AttrPage.setCurrentIndex(1)
        QtCore.QObject.connect(self.btn_close, QtCore.SIGNAL(_fromUtf8("clicked()")), Frame.close)
        QtCore.QMetaObject.connectSlotsByName(Frame)
        Frame.setTabOrder(self.btn_adduser, self.btn_deluser)
        Frame.setTabOrder(self.btn_deluser, self.edt_username)
        Frame.setTabOrder(self.edt_username, self.edt_passward)
        Frame.setTabOrder(self.edt_passward, self.edt_confirmpass)
        Frame.setTabOrder(self.edt_confirmpass, self.btn_saveinfo)
        Frame.setTabOrder(self.btn_saveinfo, self.btn_cancel)
        Frame.setTabOrder(self.btn_cancel, self.btn_close)

    def retranslateUi(self, Frame):
        Frame.setWindowTitle(QtGui.QApplication.translate("Frame", "用户管理", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_adduser.setText(QtGui.QApplication.translate("Frame", "添加用户", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_deluser.setText(QtGui.QApplication.translate("Frame", "删除用户", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_close.setText(QtGui.QApplication.translate("Frame", "关闭", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("Frame", "用户属性", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Frame", "密码", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Frame", "用户名", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_revise.setText(QtGui.QApplication.translate("Frame", "保存", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_resetting.setText(QtGui.QApplication.translate("Frame", "取消", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("Frame", "创建时间", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("Frame", "类别", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Frame", "添加用户", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Frame", "密码", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Frame", "用户名", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_saveinfo.setText(QtGui.QApplication.translate("Frame", "保存", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_cancel.setText(QtGui.QApplication.translate("Frame", "取消", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Frame", "确认密码", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Frame", "类别", None, QtGui.QApplication.UnicodeUTF8))

