# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_management.ui'
#
# Created: Wed Aug 22 17:05:45 2012
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(788, 557)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(2, 4, 741, 111))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.edtStart = QtGui.QLineEdit(self.groupBox)
        self.edtStart.setGeometry(QtCore.QRect(80, 24, 120, 20))
        self.edtStart.setObjectName(_fromUtf8("edtStart"))
        self.edtEnd = QtGui.QLineEdit(self.groupBox)
        self.edtEnd.setGeometry(QtCore.QRect(250, 24, 120, 20))
        self.edtEnd.setObjectName(_fromUtf8("edtEnd"))
        self.label_5 = QtGui.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(30, 30, 41, 16))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(217, 25, 31, 16))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.edtDayHours = QtGui.QLineEdit(self.groupBox)
        self.edtDayHours.setGeometry(QtCore.QRect(460, 25, 120, 20))
        self.edtDayHours.setObjectName(_fromUtf8("edtDayHours"))
        self.edtGeoRect = QtGui.QLineEdit(self.groupBox)
        self.edtGeoRect.setGeometry(QtCore.QRect(80, 50, 291, 20))
        self.edtGeoRect.setObjectName(_fromUtf8("edtGeoRect"))
        self.label_7 = QtGui.QLabel(self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(20, 54, 54, 12))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_8 = QtGui.QLabel(self.groupBox)
        self.label_8.setGeometry(QtCore.QRect(390, 24, 61, 16))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.btnOpenMap = QtGui.QPushButton(self.groupBox)
        self.btnOpenMap.setEnabled(False)
        self.btnOpenMap.setGeometry(QtCore.QRect(670, 10, 61, 31))
        self.btnOpenMap.setObjectName(_fromUtf8("btnOpenMap"))
        self.btnAbout = QtGui.QPushButton(self.groupBox)
        self.btnAbout.setGeometry(QtCore.QRect(600, 10, 61, 31))
        self.btnAbout.setObjectName(_fromUtf8("btnAbout"))
        self.txtmess = QtGui.QLabel(self.groupBox)
        self.txtmess.setGeometry(QtCore.QRect(394, 51, 61, 16))
        self.txtmess.setObjectName(_fromUtf8("txtmess"))
        self.edtMessId = QtGui.QLineEdit(self.groupBox)
        self.edtMessId.setGeometry(QtCore.QRect(460, 50, 121, 20))
        self.edtMessId.setFrame(True)
        self.edtMessId.setObjectName(_fromUtf8("edtMessId"))
        self.btnDoQuery = QtGui.QPushButton(self.groupBox)
        self.btnDoQuery.setGeometry(QtCore.QRect(390, 74, 91, 31))
        self.btnDoQuery.setStyleSheet(_fromUtf8(""))
        self.btnDoQuery.setObjectName(_fromUtf8("btnDoQuery"))
        self.cbxImageSet = QtGui.QComboBox(self.groupBox)
        self.cbxImageSet.setGeometry(QtCore.QRect(80, 80, 291, 22))
        self.cbxImageSet.setObjectName(_fromUtf8("cbxImageSet"))
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(20, 82, 51, 20))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.btnSetMessRect = QtGui.QPushButton(self.groupBox)
        self.btnSetMessRect.setGeometry(QtCore.QRect(600, 42, 61, 31))
        self.btnSetMessRect.setObjectName(_fromUtf8("btnSetMessRect"))
        self.edtMaxLines = QtGui.QLineEdit(self.groupBox)
        self.edtMaxLines.setGeometry(QtCore.QRect(552, 80, 61, 20))
        self.edtMaxLines.setObjectName(_fromUtf8("edtMaxLines"))
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(496, 84, 54, 12))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.listRecords = QtGui.QTreeWidget(self.centralwidget)
        self.listRecords.setGeometry(QtCore.QRect(2, 157, 781, 351))
        self.listRecords.setStyleSheet(_fromUtf8("font: 11pt \"微软雅黑\";\n"
"color: rgb(0, 0, 127);\n"
""))
        self.listRecords.setObjectName(_fromUtf8("listRecords"))
        self.listRecords.headerItem().setText(0, _fromUtf8("1"))
        self.ckShowPlayWnd = QtGui.QCheckBox(self.centralwidget)
        self.ckShowPlayWnd.setGeometry(QtCore.QRect(624, 87, 121, 16))
        self.ckShowPlayWnd.setObjectName(_fromUtf8("ckShowPlayWnd"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(2, 127, 91, 16))
        self.label.setObjectName(_fromUtf8("label"))
        self.btnRemove = QtGui.QPushButton(self.centralwidget)
        self.btnRemove.setGeometry(QtCore.QRect(77, 127, 75, 23))
        self.btnRemove.setObjectName(_fromUtf8("btnRemove"))
        self.btnShowTags = QtGui.QPushButton(self.centralwidget)
        self.btnShowTags.setGeometry(QtCore.QRect(396, 126, 75, 23))
        self.btnShowTags.setObjectName(_fromUtf8("btnShowTags"))
        self.btnMoveToTask = QtGui.QPushButton(self.centralwidget)
        self.btnMoveToTask.setGeometry(QtCore.QRect(160, 127, 75, 23))
        self.btnMoveToTask.setObjectName(_fromUtf8("btnMoveToTask"))
        self.btnImagePlay = QtGui.QPushButton(self.centralwidget)
        self.btnImagePlay.setGeometry(QtCore.QRect(320, 127, 75, 23))
        self.btnImagePlay.setObjectName(_fromUtf8("btnImagePlay"))
        self.btnRemoveFromTask = QtGui.QPushButton(self.centralwidget)
        self.btnRemoveFromTask.setGeometry(QtCore.QRect(240, 128, 75, 23))
        self.btnRemoveFromTask.setObjectName(_fromUtf8("btnRemoveFromTask"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 788, 23))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuCcj = QtGui.QMenu(self.menubar)
        self.menuCcj.setObjectName(_fromUtf8("menuCcj"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.miUserMgr = QtGui.QAction(MainWindow)
        self.miUserMgr.setObjectName(_fromUtf8("miUserMgr"))
        self.miTask = QtGui.QAction(MainWindow)
        self.miTask.setObjectName(_fromUtf8("miTask"))
        self.miServerStatus = QtGui.QAction(MainWindow)
        self.miServerStatus.setObjectName(_fromUtf8("miServerStatus"))
        self.miChangePwd = QtGui.QAction(MainWindow)
        self.miChangePwd.setObjectName(_fromUtf8("miChangePwd"))
        self.miExit = QtGui.QAction(MainWindow)
        self.miExit.setObjectName(_fromUtf8("miExit"))
        self.menuCcj.addAction(self.miUserMgr)
        self.menuCcj.addAction(self.miTask)
        self.menuCcj.addAction(self.miServerStatus)
        self.menuCcj.addAction(self.miChangePwd)
        self.menuCcj.addSeparator()
        self.menuCcj.addAction(self.miExit)
        self.menubar.addAction(self.menuCcj.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "影像控制台 v0.2.0  Fks(F8,F9,F10)", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "条件查询", None, QtGui.QApplication.UnicodeUTF8))
        self.edtStart.setInputMask(QtGui.QApplication.translate("MainWindow", "9999-99-99; ", None, QtGui.QApplication.UnicodeUTF8))
        self.edtStart.setText(QtGui.QApplication.translate("MainWindow", "2012-02-10", None, QtGui.QApplication.UnicodeUTF8))
        self.edtEnd.setInputMask(QtGui.QApplication.translate("MainWindow", "9999-99-99; ", None, QtGui.QApplication.UnicodeUTF8))
        self.edtEnd.setText(QtGui.QApplication.translate("MainWindow", "2013-06-10", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "开始", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "结束", None, QtGui.QApplication.UnicodeUTF8))
        self.edtDayHours.setInputMask(QtGui.QApplication.translate("MainWindow", "99-99; ", None, QtGui.QApplication.UnicodeUTF8))
        self.edtDayHours.setText(QtGui.QApplication.translate("MainWindow", "8-20", None, QtGui.QApplication.UnicodeUTF8))
        self.edtGeoRect.setText(QtGui.QApplication.translate("MainWindow", "12,30,177,45", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "地理视野", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "日区间", None, QtGui.QApplication.UnicodeUTF8))
        self.btnOpenMap.setText(QtGui.QApplication.translate("MainWindow", "打开地图", None, QtGui.QApplication.UnicodeUTF8))
        self.btnAbout.setText(QtGui.QApplication.translate("MainWindow", "关于...", None, QtGui.QApplication.UnicodeUTF8))
        self.txtmess.setText(QtGui.QApplication.translate("MainWindow", "图幅编号", None, QtGui.QApplication.UnicodeUTF8))
        self.edtMessId.setText(QtGui.QApplication.translate("MainWindow", "H51F009013", None, QtGui.QApplication.UnicodeUTF8))
        self.btnDoQuery.setText(QtGui.QApplication.translate("MainWindow", "查询", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "计划范围", None, QtGui.QApplication.UnicodeUTF8))
        self.btnSetMessRect.setText(QtGui.QApplication.translate("MainWindow", "定位", None, QtGui.QApplication.UnicodeUTF8))
        self.edtMaxLines.setInputMask(QtGui.QApplication.translate("MainWindow", "9999; ", None, QtGui.QApplication.UnicodeUTF8))
        self.edtMaxLines.setText(QtGui.QApplication.translate("MainWindow", "50", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "最大行数", None, QtGui.QApplication.UnicodeUTF8))
        self.ckShowPlayWnd.setText(QtGui.QApplication.translate("MainWindow", "显示/隐藏播放", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "影像记录", None, QtGui.QApplication.UnicodeUTF8))
        self.btnRemove.setText(QtGui.QApplication.translate("MainWindow", "物理删除", None, QtGui.QApplication.UnicodeUTF8))
        self.btnShowTags.setText(QtGui.QApplication.translate("MainWindow", "显示标记", None, QtGui.QApplication.UnicodeUTF8))
        self.btnMoveToTask.setText(QtGui.QApplication.translate("MainWindow", "移动到计划", None, QtGui.QApplication.UnicodeUTF8))
        self.btnImagePlay.setText(QtGui.QApplication.translate("MainWindow", "播放", None, QtGui.QApplication.UnicodeUTF8))
        self.btnRemoveFromTask.setText(QtGui.QApplication.translate("MainWindow", "移出计划", None, QtGui.QApplication.UnicodeUTF8))
        self.menuCcj.setTitle(QtGui.QApplication.translate("MainWindow", "管理", None, QtGui.QApplication.UnicodeUTF8))
        self.miUserMgr.setText(QtGui.QApplication.translate("MainWindow", "用户管理", None, QtGui.QApplication.UnicodeUTF8))
        self.miTask.setText(QtGui.QApplication.translate("MainWindow", "计划任务", None, QtGui.QApplication.UnicodeUTF8))
        self.miServerStatus.setText(QtGui.QApplication.translate("MainWindow", "服务器状态", None, QtGui.QApplication.UnicodeUTF8))
        self.miChangePwd.setText(QtGui.QApplication.translate("MainWindow", "更改用户密码", None, QtGui.QApplication.UnicodeUTF8))
        self.miExit.setText(QtGui.QApplication.translate("MainWindow", "系统退出", None, QtGui.QApplication.UnicodeUTF8))

